version: "3"
services:
  #  Create a service named db.
  emt-db:
    #   Use the Docker Image postgres. This will pull the newest release.
    image: "postgres"
    #   Give the container the name my_postgres. You can change to something else.
    container_name: "emt2021_eshop"
    #   Set up the username, password, and database name. You can change these values.
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=at
      - POSTGRES_DB=emtlab
    #   Maps port 5432 (localhost) to port 5432 on the container. You can change the ports to fix your needs.
    ports:
      - "54322:5432"
    #   Set a volume some that database is not lost after shutting down the container.
    #   I used the name postgres-data, but you can change it to something else.
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
